# Welcome to Jekyll!
#

title: Random Duff
email: randn@randomduff.info
#description: >- # this means to ignore newlines until "baseurl:"
description: | 
  Non-linear, potentially random, content.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  veloduff 

# Build settings
theme: minima
